# Generated by Django 2.1.4 on 2018-12-23 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', 'Only lower case, upper case letters, numbers and spaces are allowed')]),
        ),
    ]
