# Generated by Django 2.1.4 on 2018-12-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181223_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
